/*
 * Golden-master determinism tests.
 *
 * The fixtures were generated by running the ORIGINAL browser simulation
 * (fpv-sim/index.html) headless — see scripts/generate-goldens.mjs — and
 * cross-checked against the untouched sim in a real browser. The engine
 * must reproduce every featured engagement EXACTLY: event log string
 * equality, tick-exact end time, float-exact fix quality.
 *
 * If one of these tests fails, simulation behavior has diverged from the
 * browser version. That is a defect by definition, even if the new behavior
 * looks "better" — fix the engine, do not regenerate the fixtures, unless
 * the upstream sim itself changed (then regenerate AND record the new
 * upstream commit in docs/upstream/SNAPSHOT.md).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runEngagement } from "../src/engine/index.js";

interface GoldenTeam {
  lobs: number;
  nodes: { id: string; ul_intercepts: number; dl_intercepts: number }[];
  fix: {
    x: number; y: number; cep: number; formalCep: number; geomCep: number;
    jitter: number; cutDeg: number; balance: number;
  } | null;
  drone: { state: string; batt: number; x: number; y: number };
  gcs: { destroyed: boolean; x: number; y: number };
}

interface GoldenRun {
  seed: number;
  winner: string | null;
  endT: number | null;
  duration: number;
  phases: { t: number; phase: string }[];
  teams: { BLUFOR: GoldenTeam; OPFOR: GoldenTeam };
  events: { t: number; side: string; text: string }[];
}

const here = path.dirname(fileURLToPath(import.meta.url)); // dist/test at runtime
const fixturePath = path.resolve(here, "..", "..", "test", "fixtures", "golden-seeds.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as { runs: GoldenRun[] };

assert.equal(fixture.runs.length, 5, "expected the five featured scenario seeds");

for (const golden of fixture.runs) {
  test(`seed ${golden.seed} reproduces the browser engagement exactly`, () => {
    const r = runEngagement(golden.seed);

    // Outcome and clock.
    assert.equal(r.outcome.result, golden.winner ?? "STALEMATE");
    assert.equal(r.duration_s, golden.duration);
    if (golden.endT !== null) assert.equal(r.duration_s, golden.endT);

    // Event log: full string equality, every entry, in order.
    assert.deepEqual(r.events, golden.events);

    // Phase timeline.
    assert.deepEqual(r.phase_timeline, golden.phases);

    for (const side of ["BLUFOR", "OPFOR"] as const) {
      const gt = golden.teams[side];
      const et = r.teams[side];
      assert.equal(et.lobs_held, gt.lobs, `${side} LOB count`);
      assert.deepEqual(et.nodes, gt.nodes, `${side} per-node intercept counts`);
      // Fix quality: float-exact — same expression order, same doubles.
      if (gt.fix === null) {
        assert.equal(et.fix, null, `${side} should have no solved fix`);
      } else {
        assert.ok(et.fix, `${side} should have a solved fix`);
        assert.equal(et.fix.x, gt.fix.x);
        assert.equal(et.fix.y, gt.fix.y);
        assert.equal(et.fix.cep_m, gt.fix.cep);
        assert.equal(et.fix.formal_cep_m, gt.fix.formalCep);
        assert.equal(et.fix.geom_cep_m, gt.fix.geomCep);
        assert.equal(et.fix.jitter_m, gt.fix.jitter);
        assert.equal(et.fix.cut_deg, gt.fix.cutDeg);
        assert.equal(et.fix.balance, gt.fix.balance);
      }
      assert.equal(et.drone.end_state, gt.drone.state, `${side} drone end state`);
      assert.equal(et.drone.battery_pct, gt.drone.batt, `${side} drone battery`);
      assert.equal(et.drone.x, gt.drone.x);
      assert.equal(et.drone.y, gt.drone.y);
      assert.equal(et.gcs.destroyed, gt.gcs.destroyed, `${side} GCS state`);
      assert.equal(et.gcs.x, gt.gcs.x);
      assert.equal(et.gcs.y, gt.gcs.y);
    }
  });
}

test("same seed and overrides are reproducible; instances are isolated", () => {
  const a = runEngagement(4242);
  const b = runEngagement(4242);
  assert.deepEqual(a, b, "two runs of the same seed must be identical");

  // A run with different overrides in between must not perturb anything
  // (fresh Simulation per run — no shared mutable state).
  runEngagement(4242, { TEAMS: { OPFOR: { videoOff: 7, videoOn: 3 } } });
  const c = runEngagement(4242);
  assert.deepEqual(a, c, "an interleaved overridden run must not affect a stock run");
});
