/*
 * Golden-master determinism tests, tactical mode.
 *
 * Same contract as golden.test.ts, against the tactical fixture set
 * (test/fixtures/golden-seeds-tactical.json): the fixtures were generated by
 * running the ORIGINAL browser simulation headless with
 * resetSim(seed, "tactical") — see scripts/generate-goldens.mjs — and the
 * engine must reproduce every featured tactical engagement EXACTLY: event
 * log string equality, tick-exact end time, float-exact fix quality and
 * per-airframe state, identical sortie tallies.
 *
 * If one of these tests fails, tactical-mode behavior has diverged from the
 * browser version. Fix the engine, do not regenerate the fixtures, unless
 * the upstream sim itself changed (then regenerate AND record the new
 * upstream commit in docs/upstream/SNAPSHOT.md).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runEngagement } from "../src/engine/index.js";

interface GoldenTacticalDrone {
  id: string; role: string; sortie: number; launched: boolean;
  state: string; batt: number; x: number; y: number;
}

interface GoldenTacticalTeam {
  lobs: number;
  nodes: { id: string; ul_intercepts: number; dl_intercepts: number }[];
  fix: {
    x: number; y: number; cep: number; formalCep: number; geomCep: number;
    jitter: number; cutDeg: number; balance: number;
  } | null;
  flown: number;
  delivered: number;
  drones: GoldenTacticalDrone[];
  gcs: { destroyed: boolean; x: number; y: number };
}

interface GoldenTacticalRun {
  seed: number;
  winner: string | null;
  stalemate: boolean;
  killer: string | null;
  endT: number | null;
  duration: number;
  phases: { t: number; phase: string }[];
  objective: { x: number; y: number; r: number; name: string };
  teams: { BLUFOR: GoldenTacticalTeam; OPFOR: GoldenTacticalTeam };
  events: { t: number; side: string; text: string }[];
}

const here = path.dirname(fileURLToPath(import.meta.url)); // dist/test at runtime
const fixturePath = path.resolve(here, "..", "..", "test", "fixtures", "golden-seeds-tactical.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as { runs: GoldenTacticalRun[] };

assert.equal(fixture.runs.length, 6, "expected the six featured tactical scenario seeds");

for (const golden of fixture.runs) {
  test(`tactical seed ${golden.seed} reproduces the browser engagement exactly`, () => {
    const r = runEngagement(golden.seed, undefined, { mode: "tactical" });

    // Outcome and clock.
    assert.equal(r.mode, "tactical");
    assert.equal(r.outcome.result, golden.winner ?? "STALEMATE");
    assert.equal(r.outcome.reason, golden.winner ? "gcs_destroyed" : "packages_expended");
    assert.equal(r.duration_s, golden.duration);
    if (golden.endT !== null) assert.equal(r.duration_s, golden.endT);
    assert.equal(r.killer_id ?? null, golden.killer);

    // The contested objective (jittered per seed).
    assert.ok(r.objective, "tactical results carry the objective");
    assert.equal(r.objective.x, golden.objective.x);
    assert.equal(r.objective.y, golden.objective.y);
    assert.equal(r.objective.radius_m, golden.objective.r);
    assert.equal(r.objective.name, golden.objective.name);

    // Event log: full string equality, every entry, in order.
    assert.deepEqual(r.events, golden.events);

    // Phase timeline.
    assert.deepEqual(r.phase_timeline, golden.phases);

    for (const side of ["BLUFOR", "OPFOR"] as const) {
      const gt = golden.teams[side];
      const et = r.teams[side];
      assert.equal(et.lobs_held, gt.lobs, `${side} LOB count`);
      assert.deepEqual(et.nodes, gt.nodes, `${side} per-node intercept counts`);
      // Fix quality: float-exact — same expression order, same doubles.
      if (gt.fix === null) {
        assert.equal(et.fix, null, `${side} should have no solved fix`);
      } else {
        assert.ok(et.fix, `${side} should have a solved fix`);
        assert.equal(et.fix.x, gt.fix.x);
        assert.equal(et.fix.y, gt.fix.y);
        assert.equal(et.fix.cep_m, gt.fix.cep);
        assert.equal(et.fix.formal_cep_m, gt.fix.formalCep);
        assert.equal(et.fix.geom_cep_m, gt.fix.geomCep);
        assert.equal(et.fix.jitter_m, gt.fix.jitter);
        assert.equal(et.fix.cut_deg, gt.fix.cutDeg);
        assert.equal(et.fix.balance, gt.fix.balance);
      }
      // Sortie tallies and the whole package, airframe for airframe.
      assert.equal(et.sorties_flown, gt.flown, `${side} sorties flown`);
      assert.equal(et.strikes_delivered, gt.delivered, `${side} strikes delivered`);
      assert.equal(et.drone, null, `${side} has no orbit drone in tactical mode`);
      const edrones = et.drones!;
      assert.ok(edrones, `${side} reports its package`);
      assert.equal(edrones.length, gt.drones.length, `${side} package size`);
      for (let i = 0; i < gt.drones.length; i++) {
        const gd = gt.drones[i], ed = edrones[i];
        assert.equal(ed.id, gd.id);
        assert.equal(ed.role, gd.role, `${gd.id} role`);
        assert.equal(ed.sortie, gd.sortie, `${gd.id} sortie`);
        assert.equal(ed.launched, gd.launched, `${gd.id} launched`);
        assert.equal(ed.end_state, gd.state, `${gd.id} end state`);
        assert.equal(ed.battery_pct, gd.batt, `${gd.id} battery`);
        assert.equal(ed.x, gd.x, `${gd.id} x`);
        assert.equal(ed.y, gd.y, `${gd.id} y`);
      }
      assert.equal(et.gcs.destroyed, gt.gcs.destroyed, `${side} GCS state`);
      assert.equal(et.gcs.x, gt.gcs.x);
      assert.equal(et.gcs.y, gt.gcs.y);
    }
  });
}

test("tactical mode: same seed and overrides are reproducible; instances are isolated", () => {
  const a = runEngagement(4242, undefined, { mode: "tactical" });
  const b = runEngagement(4242, undefined, { mode: "tactical" });
  assert.deepEqual(a, b, "two tactical runs of the same seed must be identical");

  // A run with different overrides in between must not perturb anything
  // (fresh Simulation per run — no shared mutable state), and the orbit
  // engagement of the same seed must be untouched by tactical runs.
  const orbitBefore = runEngagement(4242);
  runEngagement(4242, { TACTICAL: { SORTIES: { OPFOR: 2 }, RESERVE_HUNTER: false } }, { mode: "tactical" });
  const c = runEngagement(4242, undefined, { mode: "tactical" });
  const orbitAfter = runEngagement(4242);
  assert.deepEqual(a, c, "an interleaved overridden run must not affect a stock run");
  assert.deepEqual(orbitBefore, orbitAfter, "tactical runs must not perturb orbit runs");
});

test("tactical config overrides change the plan deterministically", () => {
  const stock = runEngagement(7, undefined, { mode: "tactical" });
  const small = runEngagement(7, { TACTICAL: { SORTIES: { BLUFOR: 2, OPFOR: 2 } } }, { mode: "tactical" });
  assert.equal(stock.teams.BLUFOR.drones!.length, 6, "5 strikes + 1 reserve hunter");
  assert.equal(small.teams.BLUFOR.drones!.length, 3, "2 strikes + 1 reserve hunter");
  const noReserve = runEngagement(7, { TACTICAL: { RESERVE_HUNTER: false } }, { mode: "tactical" });
  assert.equal(noReserve.teams.BLUFOR.drones!.length, 5, "no reserve airframe");
});
