/*
 * Golden-master determinism tests.
 *
 * The fixtures were generated by running the ORIGINAL browser simulation
 * (fpv-sim/index.html) headless — see scripts/generate-goldens.mjs — and
 * cross-checked against the untouched sim in a real browser. The engine
 * must reproduce every featured engagement EXACTLY, in both modes: event
 * log string equality, tick-exact end time, float-exact fix quality and
 * airframe positions.
 *
 * If one of these tests fails, simulation behavior has diverged from the
 * browser version. That is a defect by definition, even if the new behavior
 * looks "better" — fix the engine, do not regenerate the fixtures, unless
 * the upstream sim itself changed (then regenerate AND record the new
 * upstream commit in docs/upstream/SNAPSHOT.md).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runEngagement, type Mode } from "../src/engine/index.js";

interface GoldenAirframe {
  id: string; role: string; sortie: number; state: string; batt: number; x: number; y: number;
}

interface GoldenTeam {
  lobs: number;
  nodes: { id: string; ul_intercepts: number; dl_intercepts: number }[];
  fix: {
    x: number; y: number; cep: number; formalCep: number; geomCep: number;
    jitter: number; cutDeg: number; balance: number;
  } | null;
  drone: { state: string; batt: number; x: number; y: number } | null;
  gcs: { destroyed: boolean; x: number; y: number };
  /* Tactical runs only. */
  tactical?: {
    flown: number; delivered: number; pilots: number; hunter: string | null;
    airframes: GoldenAirframe[];
  };
}

interface GoldenRun {
  seed: number;
  mode?: Mode;               // absent on fixtures generated before tactical mode: orbit
  winner: string | null;
  stalemate?: boolean;       // tactical: the sim's own ENDEX // STALEMATE
  endT: number | null;
  duration: number;
  phases: { t: number; phase: string }[];
  teams: { BLUFOR: GoldenTeam; OPFOR: GoldenTeam };
  events: { t: number; side: string; text: string }[];
  objective?: { x: number; y: number; r: number; name: string };
}

const here = path.dirname(fileURLToPath(import.meta.url)); // dist/test at runtime
const fixturePath = path.resolve(here, "..", "..", "test", "fixtures", "golden-seeds.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as { runs: GoldenRun[] };

const modeOf = (g: GoldenRun): Mode => g.mode ?? "orbit";
assert.equal(fixture.runs.filter((g) => modeOf(g) === "orbit").length, 5, "expected the five featured orbit seeds");
// The tactical featured seeds land with the fixture regenerated against an
// upstream that has tactical mode; the count is asserted once they exist.
const tacticalRuns = fixture.runs.filter((g) => modeOf(g) === "tactical").length;
assert.ok(tacticalRuns === 0 || tacticalRuns === 6, "expected the six featured tactical seeds");

for (const golden of fixture.runs) {
  const mode = modeOf(golden);
  test(`${mode} seed ${golden.seed} reproduces the browser engagement exactly`, () => {
    const r = runEngagement(golden.seed, undefined, { mode });

    // Outcome and clock.
    assert.equal(r.mode, mode);
    assert.equal(r.outcome.result, golden.winner ?? "STALEMATE");
    if (golden.stalemate) assert.equal(r.outcome.reason, "packages_expended");
    assert.equal(r.duration_s, golden.duration);
    if (golden.endT !== null) assert.equal(r.duration_s, golden.endT);

    // Event log: full string equality, every entry, in order.
    assert.deepEqual(r.events, golden.events);

    // Phase timeline.
    assert.deepEqual(r.phase_timeline, golden.phases);

    for (const side of ["BLUFOR", "OPFOR"] as const) {
      const gt = golden.teams[side];
      const et = r.teams[side];
      assert.equal(et.lobs_held, gt.lobs, `${side} LOB count`);
      assert.deepEqual(et.nodes, gt.nodes, `${side} per-node intercept counts`);
      // Fix quality: float-exact — same expression order, same doubles.
      if (gt.fix === null) {
        assert.equal(et.fix, null, `${side} should have no solved fix`);
      } else {
        assert.ok(et.fix, `${side} should have a solved fix`);
        assert.equal(et.fix.x, gt.fix.x);
        assert.equal(et.fix.y, gt.fix.y);
        assert.equal(et.fix.cep_m, gt.fix.cep);
        assert.equal(et.fix.formal_cep_m, gt.fix.formalCep);
        assert.equal(et.fix.geom_cep_m, gt.fix.geomCep);
        assert.equal(et.fix.jitter_m, gt.fix.jitter);
        assert.equal(et.fix.cut_deg, gt.fix.cutDeg);
        assert.equal(et.fix.balance, gt.fix.balance);
      }
      if (gt.drone === null) {
        assert.equal(et.drone, null, `${side} has no single drone in ${mode} mode`);
      } else {
        assert.ok(et.drone, `${side} should have a drone`);
        assert.equal(et.drone.end_state, gt.drone.state, `${side} drone end state`);
        assert.equal(et.drone.battery_pct, gt.drone.batt, `${side} drone battery`);
        assert.equal(et.drone.x, gt.drone.x);
        assert.equal(et.drone.y, gt.drone.y);
      }
      assert.equal(et.gcs.destroyed, gt.gcs.destroyed, `${side} GCS state`);
      assert.equal(et.gcs.x, gt.gcs.x);
      assert.equal(et.gcs.y, gt.gcs.y);

      // Tactical mode: the whole package, airframe by airframe.
      if (gt.tactical) {
        assert.ok(et.tactical, `${side} should carry the tactical package result`);
        assert.equal(et.tactical.flown, gt.tactical.flown, `${side} sorties flown`);
        assert.equal(et.tactical.delivered, gt.tactical.delivered, `${side} strikes delivered`);
        assert.equal(et.tactical.pilot_stations, gt.tactical.pilots);
        assert.equal(et.tactical.hunter?.id ?? null, gt.tactical.hunter, `${side} hunter-killer`);
        assert.deepEqual(
          et.tactical.airframes.map((a) => ({
            id: a.id, role: a.role, sortie: a.sortie, state: a.end_state, batt: a.battery_pct, x: a.x, y: a.y,
          })),
          gt.tactical.airframes,
          `${side} airframes`,
        );
      } else {
        assert.equal(et.tactical, undefined, `${side} has no package in ${mode} mode`);
      }
    }

    if (golden.objective) {
      assert.ok(r.objective, "tactical run should carry the objective");
      assert.equal(r.objective.x, golden.objective.x);
      assert.equal(r.objective.y, golden.objective.y);
      assert.equal(r.objective.radius_m, golden.objective.r);
      assert.equal(r.objective.name, golden.objective.name);
    } else {
      assert.equal(r.objective, undefined);
    }
  });
}

test("same seed and overrides are reproducible; instances are isolated", () => {
  const a = runEngagement(4242);
  const b = runEngagement(4242);
  assert.deepEqual(a, b, "two runs of the same seed must be identical");

  // A run with different overrides in between must not perturb anything
  // (fresh Simulation per run — no shared mutable state).
  runEngagement(4242, { TEAMS: { OPFOR: { videoOff: 7, videoOn: 3 } } });
  const c = runEngagement(4242);
  assert.deepEqual(a, c, "an interleaved overridden run must not affect a stock run");

  // The two modes share the seed's emplacement and nothing else: a tactical
  // run in between must not perturb an orbit run, and vice versa.
  const t1 = runEngagement(4242, undefined, { mode: "tactical" });
  const d = runEngagement(4242);
  assert.deepEqual(a, d, "an interleaved tactical run must not affect an orbit run");
  const t2 = runEngagement(4242, undefined, { mode: "tactical" });
  assert.deepEqual(t1, t2, "two tactical runs of the same seed must be identical");
  assert.equal(t1.mode, "tactical");
  const gcsPos = (r: typeof a) => ({
    B: { x: r.teams.BLUFOR.gcs.x, y: r.teams.BLUFOR.gcs.y },
    O: { x: r.teams.OPFOR.gcs.x, y: r.teams.OPFOR.gcs.y },
  });
  assert.deepEqual(gcsPos(t1), gcsPos(a), "the two modes share the seed's GCS emplacement");
});
